import type { IncomingMessage, ServerResponse } from 'http';
import Stripe from 'stripe';
import crypto from 'crypto';
import { ensureUser, requireFirebaseUser } from './_firebaseAdmin';

let stripeClient: Stripe | null = null;
const attempts = new Map<string, { count: number; reset: number }>();
function getStripe() { const key = process.env.STRIPE_SECRET_KEY; if (!key) return null; if (!stripeClient) stripeClient = new Stripe(key); return stripeClient; }
async function parseBody(req: IncomingMessage): Promise<any> { return new Promise(resolve => { let body=''; req.on('data', c => body += c.toString()); req.on('end', () => { try { resolve(body ? JSON.parse(body) : {}); } catch { resolve({}); } }); }); }
function origin(req: IncomingMessage) { return process.env.ALLOWED_ORIGIN || process.env.APP_URL || String(req.headers.origin || ''); }
function sendJson(req: IncomingMessage, res: ServerResponse, status: number, data: any, extra: Record<string,string>={}) { res.writeHead(status, { 'Content-Type':'application/json', 'Cache-Control':'no-store', 'Access-Control-Allow-Origin': origin(req), 'Access-Control-Allow-Methods':'GET, POST, OPTIONS', 'Access-Control-Allow-Headers':'Content-Type, Authorization', 'Vary':'Origin', ...extra }); res.end(JSON.stringify(data)); }
function safeEqual(a:string,b:string){const aa=Buffer.from(a);const bb=Buffer.from(b);return aa.length===bb.length&&crypto.timingSafeEqual(aa,bb);}
function clientKey(req:IncomingMessage){return String(req.headers['x-forwarded-for']||req.socket.remoteAddress||'unknown').split(',')[0];}
function rateLimited(req:IncomingMessage, max=10, windowMs=60000){const key=clientKey(req);const now=Date.now();const hit=attempts.get(key);if(!hit||hit.reset<now){attempts.set(key,{count:1,reset:now+windowMs});return false;}hit.count++;return hit.count>max;}
function signAdminSession(email:string){const secret=process.env.ADMIN_SESSION_SECRET;if(!secret)return null;const expires=Date.now()+8*60*60*1000;const payload=`${email}|${expires}`;const sig=crypto.createHmac('sha256',secret).update(payload).digest('hex');return Buffer.from(`${payload}|${sig}`).toString('base64url');}
function verifyAdminSession(req:IncomingMessage){const secret=process.env.ADMIN_SESSION_SECRET;if(!secret)return false;const match=(req.headers.cookie||'').match(/(?:^|;\s*)omnypdf_admin=([^;]+)/);if(!match)return false;try{const[email,expiresRaw,sig]=Buffer.from(match[1],'base64url').toString('utf8').split('|');if(!email||!expiresRaw||!sig||Number(expiresRaw)<Date.now())return false;const expected=crypto.createHmac('sha256',secret).update(`${email}|${expiresRaw}`).digest('hex');return safeEqual(sig,expected);}catch{return false;}}

export default async function handler(req: IncomingMessage & {url?:string;method?:string}, res: ServerResponse) {
  if(req.method==='OPTIONS') return sendJson(req,res,200,{ok:true});
  const rawUrl=req.url||'';
  if(rawUrl.includes('/admin/login')){if(req.method!=='POST')return sendJson(req,res,405,{error:'Method not allowed'});if(rateLimited(req,5,15*60*1000))return sendJson(req,res,429,{error:'Too many login attempts. Try again later.'});const configuredEmail=(process.env.ADMIN_EMAIL||'').trim().toLowerCase();const configuredPassword=process.env.ADMIN_PASSWORD||'';if(!configuredEmail||!configuredPassword||!process.env.ADMIN_SESSION_SECRET)return sendJson(req,res,503,{error:'Admin authentication is not configured.'});const body=await parseBody(req);const email=String(body.email||'').trim().toLowerCase();const password=String(body.password||'');if(!safeEqual(email,configuredEmail)||!safeEqual(password,configuredPassword))return sendJson(req,res,401,{error:'Invalid administrator credentials.'});const token=signAdminSession(email);return sendJson(req,res,200,{success:true},{'Set-Cookie':`omnypdf_admin=${token}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=28800`});}
  if(rawUrl.includes('/admin/session'))return sendJson(req,res,verifyAdminSession(req)?200:401,{authenticated:verifyAdminSession(req)});
  if(rawUrl.includes('/admin/logout'))return sendJson(req,res,200,{success:true},{'Set-Cookie':'omnypdf_admin=; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=0'});
  if(rawUrl.includes('/status')||rawUrl.endsWith('/stripe'))return sendJson(req,res,200,{configured:!!process.env.STRIPE_SECRET_KEY,publishableKey:process.env.VITE_STRIPE_PUBLISHABLE_KEY||''});

  if(rawUrl.includes('/create-checkout-session')){
    try{if(rateLimited(req,10,60000))return sendJson(req,res,429,{error:'Too many checkout requests.'});const stripe=getStripe();if(!stripe)return sendJson(req,res,400,{error:'Payments are not connected yet.',isConfigured:false});const decoded=await requireFirebaseUser(req);const userRef=await ensureUser(decoded.uid,decoded.email||'',decoded.name||'');const snap=await userRef.get();const account=snap.data()||{};const body=await parseBody(req);const planId=String(body.planId||'single_use');const products:Record<string,{amount:number;title:string;description:string;mode:'payment'|'subscription';credits?:number}>={single_use:{amount:149,title:'OmniPDF Pay Once',description:'One premium OmniPDF use. No subscription.',mode:'payment',credits:1},credits_10:{amount:499,title:'OmniPDF 10 Credit Pack',description:'Ten premium OmniPDF uses. No subscription.',mode:'payment',credits:10},credits_30:{amount:999,title:'OmniPDF 30 Credit Pack',description:'Thirty premium OmniPDF uses. No subscription.',mode:'payment',credits:30},pro:{amount:900,title:'OmniPDF Pro Unlimited',description:'Unlimited daily uses and larger files up to 500 MB.',mode:'subscription'}};const product=products[planId];if(!product)return sendJson(req,res,400,{error:'Unknown purchase option.'});let customerId=account.stripeCustomerId as string|undefined;if(!customerId){const customer=await stripe.customers.create({email:decoded.email||undefined,name:decoded.name||undefined,metadata:{uid:decoded.uid}});customerId=customer.id;await userRef.set({stripeCustomerId:customerId},{merge:true});}const appUrl=(process.env.APP_URL||origin(req)).replace(/\/$/,'');const priceData:Stripe.Checkout.SessionCreateParams.LineItem.PriceData={currency:'usd',product_data:{name:product.title,description:product.description},unit_amount:product.amount};if(product.mode==='subscription')priceData.recurring={interval:'month'};const session=await stripe.checkout.sessions.create({customer:customerId,client_reference_id:decoded.uid,mode:product.mode,line_items:[{price_data:priceData,quantity:1}],success_url:`${appUrl}/?payment_status=success&session_id={CHECKOUT_SESSION_ID}&plan=${encodeURIComponent(planId)}`,cancel_url:`${appUrl}/?payment_status=cancelled`,metadata:{uid:decoded.uid,planId,credits:String(product.credits||0)}});return sendJson(req,res,200,{sessionId:session.id,url:session.url});}catch(err:any){return sendJson(req,res,err.message==='UNAUTHORIZED'?401:500,{error:err.message==='UNAUTHORIZED'?'Sign in with Google before purchasing.':err.message||'Failed to create checkout session'});}}

  if(rawUrl.includes('/verify-session')){try{const stripe=getStripe();if(!stripe)return sendJson(req,res,400,{error:'Stripe not configured'});const decoded=await requireFirebaseUser(req);const body=await parseBody(req);if(!body.sessionId)return sendJson(req,res,400,{error:'Session ID is required'});const session=await stripe.checkout.sessions.retrieve(body.sessionId);if(session.client_reference_id!==decoded.uid&&session.metadata?.uid!==decoded.uid)return sendJson(req,res,403,{error:'This checkout session does not belong to the signed-in user.'});return sendJson(req,res,200,{valid:session.payment_status==='paid'||session.status==='complete',paymentStatus:session.payment_status,status:session.status,planId:session.metadata?.planId||'',credits:Number(session.metadata?.credits||0)});}catch(err:any){return sendJson(req,res,500,{error:err.message||'Failed to verify session'});}}

  if(rawUrl.includes('/customer-portal')){try{const stripe=getStripe();if(!stripe)return sendJson(req,res,400,{error:'Stripe not configured'});const decoded=await requireFirebaseUser(req);const ref=await ensureUser(decoded.uid,decoded.email||'',decoded.name||'');const account=(await ref.get()).data()||{};if(!account.stripeCustomerId)return sendJson(req,res,400,{error:'No Stripe customer exists for this account.'});const appUrl=(process.env.APP_URL||origin(req)).replace(/\/$/,'');const portal=await stripe.billingPortal.sessions.create({customer:account.stripeCustomerId,return_url:`${appUrl}/`});return sendJson(req,res,200,{url:portal.url});}catch(err:any){return sendJson(req,res,500,{error:err.message||'Failed to open customer portal'});}}
  return sendJson(req,res,200,{status:'ok',service:'OmniPDF Serverless API',stripeConfigured:!!process.env.STRIPE_SECRET_KEY,firebaseConfigured:!!process.env.FIREBASE_PROJECT_ID});
}
